# Generated by Django 4.2.3 on 2023-08-11 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0010_rename_subject_mainsubjskill"),
        ("subjects", "0004_alter_subject_subject_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="userprofile.tutorprofile",
            ),
        ),
    ]
