# Generated by Django 4.2.3 on 2023-08-14 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0012_rename_education_studentprofile_year_group"),
        ("subjects", "0005_subject_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="userprofile.studentprofile",
            ),
        ),
    ]
