# Generated by Django 4.2.3 on 2023-08-21 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0017_message"),
        ("chat", "0003_alter_chatmessage_user_alter_room_host"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="userprofile.studentprofile",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="host",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="userprofile.studentprofile",
            ),
        ),
    ]
