# Generated by Django 4.2.3 on 2023-08-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorprofile",
            name="subjects",
            field=models.ManyToManyField(blank=True, to="userprofile.subject"),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="teaching_level",
            field=models.ManyToManyField(to="userprofile.teachinglevel"),
        ),
    ]
