# Generated by Django 4.2.3 on 2023-08-09 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("userprofile", "0002_tutorprofile_subjects_tutorprofile_teaching_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="studentuser",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="tutoruser",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
    ]
