# Generated by Django 4.2.3 on 2023-08-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "userprofile",
            "0003_studentprofile_studentuser_tutorprofile_tutoruser_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="tutorprofile",
            old_name="subjects",
            new_name="teaching_subjects",
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="interested_subjects",
            field=models.ManyToManyField(blank=True, to="userprofile.subject"),
        ),
    ]
