# Generated by Django 4.2.3 on 2023-08-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0005_alter_studentprofile_profile_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="defaultprofileimg/default.png",
                null=True,
                upload_to="student-profile-img/",
            ),
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="defaultprofileimg/default.png",
                null=True,
                upload_to="tutor-profile-img/",
            ),
        ),
    ]
