# Generated by Django 4.2.3 on 2023-08-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0007_rename_studentuser_studentprofile_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
