# Generated by Django 4.2.3 on 2023-08-11 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0008_studentprofile_name_tutorprofile_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="userprofile.tutorprofile",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="subject_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="subject_name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
