# Generated by Django 4.2.3 on 2023-08-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0009_subject_owner_subject_subject_description_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="Subject", new_name="MainSubjSkill",),
    ]
