# Generated by Django 4.2.3 on 2023-08-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0010_rename_subject_mainsubjskill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="email",
            field=models.EmailField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="first_name",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="username",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="email",
            field=models.EmailField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="first_name",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="username",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
