# Generated by Django 4.2.3 on 2023-08-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0011_alter_studentprofile_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentprofile", old_name="education", new_name="Year_group",
        ),
    ]
