# Generated by Django 4.2.3 on 2023-08-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0012_rename_education_studentprofile_year_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="parent_pro_image",
            field=models.ImageField(
                blank=True,
                default="defaultprofileimg/parentm.png",
                null=True,
                upload_to="student-parent-profile-img/",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="defaultprofileimg/studentdefault.png",
                null=True,
                upload_to="student-profile-img/",
            ),
        ),
    ]
