# Generated by Django 4.2.3 on 2023-08-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0013_studentprofile_parent_pro_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorprofile",
            name="degree",
            field=models.ImageField(
                blank=True,
                default="default-image/degree.png",
                null=True,
                upload_to="tutor-degree/",
            ),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="identification",
            field=models.ImageField(
                default="default-image/identification.png", upload_to="tutor-id/"
            ),
        ),
    ]
