# Generated by Django 4.2.3 on 2023-08-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0014_tutorprofile_degree_tutorprofile_identification"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorprofile",
            name="degree_uploaded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="identification_uploaded",
            field=models.BooleanField(default=False),
        ),
    ]
