# Generated by Django 4.2.3 on 2023-08-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0015_tutorprofile_degree_uploaded_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorprofile",
            name="profile_image_uploaded",
            field=models.BooleanField(default=False),
        ),
    ]
