# Generated by Django 4.2.3 on 2023-08-24 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0019_alter_mainsubjskill_subject_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorprofile",
            name="bio",
            field=models.TextField(
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        50, "Bio must be at least 50 characters long."
                    )
                ],
            ),
        ),
    ]
