# Generated by Django 4.2.3 on 2023-08-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0021_alter_teachinglevel_teaching_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teachinglevel",
            name="teaching_level",
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
