# Generated by Django 4.2.3 on 2023-08-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0023_remove_tutorprofile_teaching_level"),
    ]

    operations = [
        migrations.DeleteModel(name="TeachingLevel",),
    ]
